#ifndef NES_TruthTable_h
#define NES_TruthTable_h

/* NES Controller truth table
 * This is a listing of what byte is reported by the NES controller
 * based on the buttons that are being simultaneously held down.
 * This was put together through trial and error by Mick Evans
 */

#define NOTHING 255
#define A 254
#define B 253
#define A_B 252
#define SELECT 251
#define A_SELECT 250
#define B_SELECT 249
#define A_B_SELECT 248
#define START 247
#define A_START 246
#define B_START 245
#define A_B_START 244
#define SELECT_START 243
#define A_SELECT_START 242
#define B_SELECT_START 241
#define A_B_SELECT_START 240
#define UP 239
#define A_UP 238
#define B_UP 237
#define A_B_UP 236
#define SELECT_UP 235
#define A_SELECT_UP 234
#define B_SELECT_UP 233
#define A_B_SELECT_UP 232
#define START_UP 231
#define A_START_UP 230
#define B_START_UP 229
#define SELECT_START_UP 227
#define A_SELECT_START_UP 226
#define B_SELECT_START_UP 225
#define A_B_SELECT_START_UP 224
#define DOWN 223
#define A_DOWN 222
#define B_DOWN 221
#define A_B_DOWN 220
#define SELECT_DOWN 219
#define A_SELECT_DOWN 218
#define B_SELECT_DOWN 217
#define A_B_SELECT_DOWN 216
#define START_DOWN 215
#define A_START_DOWN 214
#define B_START_DOWN 213
#define A_B_START_DOWN 212
#define SELECT_START_DOWN 211
#define A_SELECT_START_DOWN 210
#define B_SELECT_START_DOWN 209
#define A_B_SELECT_START_DOWN 208
#define LEFT 191
#define A_LEFT 190
#define B_LEFT 189
#define A_B_LEFT 188
#define SELECT_LEFT 187
#define A_SELECT_LEFT 186
#define B_SELECT_LEFT 185
#define A_B_SELECT_LEFT 184
#define START_LEFT 183
#define A_START_LEFT 182
#define B_START_LEFT 181
#define A_B_START_LEFT 180
#define SELECT_START_LEFT 179
#define A_SELECT_START_LEFT 178
#define B_SELECT_START_LEFT 177
#define A_B_SELECT_START_LEFT 176
#define UP_LEFT 175
#define A_UP_LEFT 174
#define B_UP_LEFT 173
#define A_B_UP_LEFT 172
#define SELECT_UP_LEFT 171
#define A_SELECT_UP_LEFT 170
#define B_SELECT_UP_LEFT 169
#define A_B_SELECT_UP_LEFT 168
#define START_UP_LEFT 167
#define A_START_UP_LEFT 166
#define B_START_UP_LEFT 165
#define A_B_START_UP_LEFT 164
#define SELECT_START_UP_LEFT 163
#define A_SELECT_START_UP_LEFT 162
#define B_SELECT_START_UP_LEFT 161
#define A_B_SELECT_START_UP_LEFT 160
#define DOWN_LEFT 159
#define A_DOWN_LEFT 158
#define B_DOWN_LEFT 157
#define A_B_DOWN_LEFT 156
#define SELECT_DOWN_LEFT 155
#define A_SELECT_DOWN_LEFT 154
#define B_SELECT_DOWN_LEFT 153
#define A_B_SELECT_DOWN_LEFT 152
#define START_DOWN_LEFT 151
#define A_START_DOWN_LEFT 150
#define B_START_DOWN_LEFT 149
#define A_B_START_DOWN_LEFT 148
#define SELECT_START_DOWN_LEFT 147
#define A_SELECT_START_DOWN_LEFT 146
#define B_SELECT_START_DOWN_LEFT 145
#define A_B_SELECT_START_DOWN_LEFT 144
// ???there seems to be a gap here???
#define RIGHT 127
#define A_RIGHT 126
#define B_RIGHT 125
#define A_B_RIGHT 124
#define SELECT_RIGHT 123
#define A_SELECT_RIGHT 122
#define B_SELECT_RIGHT 121
#define A_B_SELECT_RIGHT 120
#define START_RIGHT 119
#define A_START_RIGHT 118
#define B_START_RIGHT 117
#define A_B_START_RIGHT 116
#define SELECT_START_RIGHT 115
#define A_SELECT_START_RIGHT 114
#define B_SELECT_START_RIGHT 113
#define A_B_SELECT_START_RIGHT 112
#define UP_RIGHT 111
#define A_UP_RIGHT 110
#define b_UP_RIGHT 109
#define A_B_UP_RIGHT 108
#define SELECT_UP_RIGHT 107
#define A_SELECT_UP_RIGHT 106
#define B_SELECT_UP_RIGHT 105
#define A_B_SELECT_UP_RIGHT 104
#define START_UP_RIGHT 103
#define A_START_UP_RIGHT 102
#define B_START_UP_RIGHT 101
#define A_B_START_UP_RIGHT 100
#define SELECT_START_UP_RIGHT 99
#define A_SELECT_START_UP_RIGHT 98
#define B_SELECT_START_UP_RIGHT 97
#define A_B_SELECT_START_UP_RIGHT 96
#define DOWN_RIGHT 95
#define A_DOWN_RIGHT 94
#define B_DOWN_RIGHT 93
#define A_B_DOWN_RIGHT 92
#define SELECT_DOWN_RIGHT 91
#define A_SELECT_DOWN_RIGHT 90
#define B_SELECT_DOWN_RIGHT 89
#define A_B_SELECT_DOWN_RIGHT 88
#define START_DOWN_RIGHT 87
#define A_START_DOWN_RIGHT 86
#define B_START_DOWN_RIGHT 85
#define A_B_START_DOWN_RIGHT 84
#define SELECT_START_DOWN_RIGHT 83
#define A_SELECT_START_DOWN_RIGHT 82
#define B_SELECT_START_DOWN_RIGHT 81
#define A_B_SELECT_START_DOWN_RIGHT 80
// ???there does not seem to be anything below here???

#endif